Update Company Logo
CorporateRewards/docs-myrewards pull request #136
Opened 2023-11-22 14:34 UTC by aharding360

Updating the CR worldwide logo to 360insights

2023-11-22 15:52 UTC, rjpaskin requested changes
Can we reduce the size of (i.e. resize) the image? The sidebar is set to a width of 230 px, so 460 px (double width for retina screens) should be ideal.

❤️ Thanks for your contribution!

2023-11-23 14:02 UTC, farisalamin approved these changes

2023-11-23 14:02 UTC, reissjohnson approved these changes

2023-11-23 16:17 UTC, rjpaskin approved these changes

2023-11-23 16:18 UTC, merged